files: (src/|tests/)
default_stages: [commit-msg, commit, push]
repos:
- hooks:
  - args:
    - --line-length
    - '80'
    id: black
    language_version: python3.10
  repo: https://github.com/psf/black
  rev: 22.10.0
- hooks:
  - additional_dependencies:
    - bandit
    - flake8-bandit
    - black
    - pycodestyle
    - mccabe
    - pyflakes
    - flake8-black
    - flake8-comprehensions
    - flake8-class-attributes-order
    - flake8-bugbear
    - wemake-python-styleguide
    - flake8-simplify
    - flake8-pie
    - flake8-use-pathlib
    - flake8-use-fstring
    - flake8-print
    - flake8-no-implicit-concat
    - flake8-pytest-style
    - Flake8-AAA
    - flake8-docstring-checker
    - flake8-docstrings
    - flake8-length
    - flake8-functions
    - flake8-expression-complexity
    - flake8-cognitive-complexity
    - flake8-annotations-complexity
    - flake8-type-checking
    id: flake8
  repo: https://github.com/pycqa/flake8
  rev: 6.0.0
- hooks:
  - id: trailing-whitespace
  - id: check-ast
  - id: check-builtin-literals
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-json
  - id: check-symlinks
  - id: check-toml
  - id: check-yaml
  - id: no-commit-to-branch
    args:
      - --branch
      - main
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
- hooks:
  - additional_dependencies:
    - types-dataclasses
    - types-PyYAML
    - pytest
    - pandas-stubs
    - types-beautifulsoup4
    id: mypy
  repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.991
- hooks:
  - id: darglint
  repo: https://github.com/terrencepreilly/darglint
  rev: v1.8.1
- hooks:
  - id: tryceratops
  repo: https://github.com/guilatrova/tryceratops
  rev: v1.1.0
- hooks:
  - id: pyroma
  repo: https://github.com/regebro/pyroma
  rev: '4.1'
- hooks:
  - args:
    - src
    - setup.py
    - .vulture.py
    - --min-confidence
    - '59'
    id: vulture
  repo: https://github.com/jendrikseipp/vulture
  rev: v2.6
- hooks:
  - id: sourcery
  repo: https://github.com/sourcery-ai/sourcery
  rev: v1.0.1
- hooks:
  - id: pylint
    entry: pylint
    name: pylint
    language: system
    types:
      - python
    args:
      - --rcfile=pylintrc
  - id: histdatacom
    entry: histdatacom
    language: system
    name: histdatacom
    pass_filenames: false
    always_run: True
    verbose: True
    types:
      - python
    args:
      - -A
  - id: coverage-run
    name: coverage-run
    entry: coverage
    language: system
    args: ["run"]
    pass_filenames: false
    always_run: True
    types:
      - python
  - id: coverage-combine
    name: coverage-combine
    entry: coverage
    language: system
    args: ["combine"]
    pass_filenames: false
    always_run: True
    types:
      - python
  - id: coverage-report
    name: coverage-report
    entry: coverage
    language: system
    args: ["report"]
    pass_filenames: false
    always_run: True
    verbose: True
    types:
      - python
  - id: coverage-rm
    name: coverage-rm
    entry: rm
    language: system
    args: ["-f", ".coverage"]
    pass_filenames: false
    always_run: True
  repo: local
- repo: https://github.com/commitizen-tools/commitizen
  rev: v2.37.1
  hooks:
    - id: commitizen
    - id: commitizen-branch
      stages: [push]
