output-format: json

strictness: veryhigh

ignore-paths:
  - build
  - dist
  - data
  - venv
  - .vscode
  - mp_influx_samp.py

pycodestyle:
  disable:
    - E501
    - E122
    - W605

pylint:
  disable:
    - line-too-long
    - too-many-arguments
    - too-many-locals
    - too-few-public-methods
    - too-many-instance-attributes